### ISSUE TITLE
Setup review_list page - Important

### ISSUE THREAD

**Issue by ty-labs** [CMU-313/fall-2021-hw2-the-brogrammers#36]
The cabinets page has a list view when cabinets are created. Mimick this feature for the reviews app (change actual information to include aggregations).

**Comment by dyou3968** [comment]
@tyjlowe This is the other issue that you created right? I think we can close this now.

**Comment by ty-labs** [comment]
@dyou3968 yes, this was completed a while back but safe to close now!
